package com.noreasonexception.datanuke.app.threadRunner.error;

public class LoopPrepareException extends Exception {
    public LoopPrepareException(String s, Throwable throwable) {
        super(s, throwable);
    }
}
